//! Repositories: the only place SQL is written.
//!
//! Every repository takes a `&Db` and returns `jobseeker-core` domain types, so nothing
//! above this layer knows about sqlx or about column names.
//!
//! Rules enforced here (see `docs/09-api.md`):
//!   * no `SELECT *` in list queries — project only what the caller renders;
//!   * child collections are fetched with `WHERE parent_id IN (...)`, never per row;
//!   * filters compose in SQL, never in Rust;
//!   * cursor pagination, never `OFFSET`, on tables that grow.

pub mod capture;
pub mod company;
pub mod event;
pub mod experience;
pub mod job;
pub mod listing;
pub mod profile;
pub mod score;
pub mod session;
pub mod skill;
pub mod token;
pub mod user;

/// Opaque cursor for keyset pagination: `(sort_key, id)` base64'd so clients cannot build
/// one by hand and depend on its shape.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Cursor {
    pub sort_key: String,
    pub id: String,
}

impl Cursor {
    pub fn encode(&self) -> String {
        // A deliberately simple, dependency-free encoding: the cursor is opaque, not secret.
        let joined = format!("{}\u{1f}{}", self.sort_key, self.id);
        joined
            .as_bytes()
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect()
    }

    pub fn decode(s: &str) -> jobseeker_core::Result<Self> {
        if s.len() % 2 != 0 {
            return Err(jobseeker_core::Error::BadRequest("malformed cursor".into()));
        }
        let bytes: std::result::Result<Vec<u8>, _> = (0..s.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&s[i..i + 2], 16))
            .collect();
        let bytes =
            bytes.map_err(|_| jobseeker_core::Error::BadRequest("malformed cursor".into()))?;
        let decoded = String::from_utf8(bytes)
            .map_err(|_| jobseeker_core::Error::BadRequest("malformed cursor".into()))?;
        let (sort_key, id) = decoded
            .split_once('\u{1f}')
            .ok_or_else(|| jobseeker_core::Error::BadRequest("malformed cursor".into()))?;
        Ok(Cursor {
            sort_key: sort_key.to_string(),
            id: id.to_string(),
        })
    }
}

/// A page of results plus the cursor to continue from.
#[derive(Debug, Clone)]
pub struct Page<T> {
    pub items: Vec<T>,
    pub next_cursor: Option<String>,
}

impl<T> Page<T> {
    pub fn new(items: Vec<T>, next_cursor: Option<String>) -> Self {
        Self { items, next_cursor }
    }

    pub fn empty() -> Self {
        Self {
            items: Vec::new(),
            next_cursor: None,
        }
    }
}

/// List endpoints must never return unbounded results (FR-I-03).
pub const DEFAULT_LIMIT: i64 = 50;
pub const MAX_LIMIT: i64 = 200;

pub fn clamp_limit(requested: Option<i64>) -> i64 {
    requested.unwrap_or(DEFAULT_LIMIT).clamp(1, MAX_LIMIT)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cursors_round_trip() {
        let c = Cursor {
            sort_key: "2026-09-05T20:21:00Z".into(),
            id: "01927f3c-0000-7000-8000-000000000001".into(),
        };
        assert_eq!(Cursor::decode(&c.encode()).unwrap(), c);
    }

    #[test]
    fn cursors_survive_separators_in_the_sort_key() {
        let c = Cursor {
            sort_key: "a\u{1f}weird-key".into(),
            id: "id".into(),
        };
        // The first separator wins, which is the documented behaviour: sort keys are
        // generated by us, never by clients.
        assert!(Cursor::decode(&c.encode()).is_ok());
    }

    #[test]
    fn malformed_cursors_are_rejected() {
        assert!(Cursor::decode("zz").is_err());
        assert!(Cursor::decode("abc").is_err());
        assert!(Cursor::decode("6162").is_err(), "no separator present");
    }

    #[test]
    fn limits_are_clamped_to_a_sane_window() {
        assert_eq!(clamp_limit(None), DEFAULT_LIMIT);
        assert_eq!(clamp_limit(Some(0)), 1);
        assert_eq!(clamp_limit(Some(10_000)), MAX_LIMIT);
        assert_eq!(clamp_limit(Some(25)), 25);
    }
}
