/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as JobsRouteImport } from './routes/jobs';
import { Route as PipelineRouteImport } from './routes/pipeline';
import { Route as ProfileRouteImport } from './routes/profile';
import { Route as TodayRouteImport } from './routes/today';
import { Route as JobsJobIdRouteImport } from './routes/jobs_.$jobId';
import { Route as JobsCompareRouteImport } from './routes/jobs_.compare';
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId';
import { Route as JobsJobIdIndexRouteImport } from './routes/jobs_.$jobId.index';
import { Route as JobsJobIdDescriptionRouteImport } from './routes/jobs_.$jobId.description';
import { Route as JobsJobIdMatchRouteImport } from './routes/jobs_.$jobId.match';
import { Route as JobsJobIdRequirementsRouteImport } from './routes/jobs_.$jobId.requirements';
import { Route as JobsJobIdSourcesRouteImport } from './routes/jobs_.$jobId.sources';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any);
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any);
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any);
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs_/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any);
const JobsCompareRoute = JobsCompareRouteImport.update({
  id: '/jobs_/compare',
  path: '/jobs/compare',
  getParentRoute: () => rootRouteImport,
} as any);
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any);
const JobsJobIdIndexRoute = JobsJobIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsJobIdRoute,
} as any);
const JobsJobIdDescriptionRoute = JobsJobIdDescriptionRouteImport.update({
  id: '/description',
  path: '/description',
  getParentRoute: () => JobsJobIdRoute,
} as any);
const JobsJobIdMatchRoute = JobsJobIdMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => JobsJobIdRoute,
} as any);
const JobsJobIdRequirementsRoute = JobsJobIdRequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => JobsJobIdRoute,
} as any);
const JobsJobIdSourcesRoute = JobsJobIdSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => JobsJobIdRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/jobs': typeof JobsRoute;
  '/pipeline': typeof PipelineRoute;
  '/profile': typeof ProfileRoute;
  '/today': typeof TodayRoute;
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren;
  '/jobs/compare': typeof JobsCompareRoute;
  '/tasks/$taskId': typeof TasksTaskIdRoute;
  '/jobs/$jobId/description': typeof JobsJobIdDescriptionRoute;
  '/jobs/$jobId/match': typeof JobsJobIdMatchRoute;
  '/jobs/$jobId/requirements': typeof JobsJobIdRequirementsRoute;
  '/jobs/$jobId/sources': typeof JobsJobIdSourcesRoute;
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/jobs': typeof JobsRoute;
  '/pipeline': typeof PipelineRoute;
  '/profile': typeof ProfileRoute;
  '/today': typeof TodayRoute;
  '/jobs/compare': typeof JobsCompareRoute;
  '/tasks/$taskId': typeof TasksTaskIdRoute;
  '/jobs/$jobId/description': typeof JobsJobIdDescriptionRoute;
  '/jobs/$jobId/match': typeof JobsJobIdMatchRoute;
  '/jobs/$jobId/requirements': typeof JobsJobIdRequirementsRoute;
  '/jobs/$jobId/sources': typeof JobsJobIdSourcesRoute;
  '/jobs/$jobId': typeof JobsJobIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/jobs': typeof JobsRoute;
  '/pipeline': typeof PipelineRoute;
  '/profile': typeof ProfileRoute;
  '/today': typeof TodayRoute;
  '/jobs_/$jobId': typeof JobsJobIdRouteWithChildren;
  '/jobs_/compare': typeof JobsCompareRoute;
  '/tasks/$taskId': typeof TasksTaskIdRoute;
  '/jobs_/$jobId/description': typeof JobsJobIdDescriptionRoute;
  '/jobs_/$jobId/match': typeof JobsJobIdMatchRoute;
  '/jobs_/$jobId/requirements': typeof JobsJobIdRequirementsRoute;
  '/jobs_/$jobId/sources': typeof JobsJobIdSourcesRoute;
  '/jobs_/$jobId/': typeof JobsJobIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/jobs'
    | '/pipeline'
    | '/profile'
    | '/today'
    | '/jobs/$jobId'
    | '/jobs/compare'
    | '/tasks/$taskId'
    | '/jobs/$jobId/description'
    | '/jobs/$jobId/match'
    | '/jobs/$jobId/requirements'
    | '/jobs/$jobId/sources'
    | '/jobs/$jobId/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/jobs'
    | '/pipeline'
    | '/profile'
    | '/today'
    | '/jobs/compare'
    | '/tasks/$taskId'
    | '/jobs/$jobId/description'
    | '/jobs/$jobId/match'
    | '/jobs/$jobId/requirements'
    | '/jobs/$jobId/sources'
    | '/jobs/$jobId';
  id:
    | '__root__'
    | '/'
    | '/jobs'
    | '/pipeline'
    | '/profile'
    | '/today'
    | '/jobs_/$jobId'
    | '/jobs_/compare'
    | '/tasks/$taskId'
    | '/jobs_/$jobId/description'
    | '/jobs_/$jobId/match'
    | '/jobs_/$jobId/requirements'
    | '/jobs_/$jobId/sources'
    | '/jobs_/$jobId/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  JobsRoute: typeof JobsRoute;
  PipelineRoute: typeof PipelineRoute;
  ProfileRoute: typeof ProfileRoute;
  TodayRoute: typeof TodayRoute;
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren;
  JobsCompareRoute: typeof JobsCompareRoute;
  TasksTaskIdRoute: typeof TasksTaskIdRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/jobs': {
      id: '/jobs';
      path: '/jobs';
      fullPath: '/jobs';
      preLoaderRoute: typeof JobsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/pipeline': {
      id: '/pipeline';
      path: '/pipeline';
      fullPath: '/pipeline';
      preLoaderRoute: typeof PipelineRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/profile': {
      id: '/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/today': {
      id: '/today';
      path: '/today';
      fullPath: '/today';
      preLoaderRoute: typeof TodayRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/jobs_/$jobId': {
      id: '/jobs_/$jobId';
      path: '/jobs/$jobId';
      fullPath: '/jobs/$jobId';
      preLoaderRoute: typeof JobsJobIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/jobs_/compare': {
      id: '/jobs_/compare';
      path: '/jobs/compare';
      fullPath: '/jobs/compare';
      preLoaderRoute: typeof JobsCompareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/tasks/$taskId': {
      id: '/tasks/$taskId';
      path: '/tasks/$taskId';
      fullPath: '/tasks/$taskId';
      preLoaderRoute: typeof TasksTaskIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/jobs_/$jobId/': {
      id: '/jobs_/$jobId/';
      path: '/';
      fullPath: '/jobs/$jobId/';
      preLoaderRoute: typeof JobsJobIdIndexRouteImport;
      parentRoute: typeof JobsJobIdRoute;
    };
    '/jobs_/$jobId/description': {
      id: '/jobs_/$jobId/description';
      path: '/description';
      fullPath: '/jobs/$jobId/description';
      preLoaderRoute: typeof JobsJobIdDescriptionRouteImport;
      parentRoute: typeof JobsJobIdRoute;
    };
    '/jobs_/$jobId/match': {
      id: '/jobs_/$jobId/match';
      path: '/match';
      fullPath: '/jobs/$jobId/match';
      preLoaderRoute: typeof JobsJobIdMatchRouteImport;
      parentRoute: typeof JobsJobIdRoute;
    };
    '/jobs_/$jobId/requirements': {
      id: '/jobs_/$jobId/requirements';
      path: '/requirements';
      fullPath: '/jobs/$jobId/requirements';
      preLoaderRoute: typeof JobsJobIdRequirementsRouteImport;
      parentRoute: typeof JobsJobIdRoute;
    };
    '/jobs_/$jobId/sources': {
      id: '/jobs_/$jobId/sources';
      path: '/sources';
      fullPath: '/jobs/$jobId/sources';
      preLoaderRoute: typeof JobsJobIdSourcesRouteImport;
      parentRoute: typeof JobsJobIdRoute;
    };
  }
}

interface JobsJobIdRouteChildren {
  JobsJobIdDescriptionRoute: typeof JobsJobIdDescriptionRoute;
  JobsJobIdMatchRoute: typeof JobsJobIdMatchRoute;
  JobsJobIdRequirementsRoute: typeof JobsJobIdRequirementsRoute;
  JobsJobIdSourcesRoute: typeof JobsJobIdSourcesRoute;
  JobsJobIdIndexRoute: typeof JobsJobIdIndexRoute;
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdDescriptionRoute: JobsJobIdDescriptionRoute,
  JobsJobIdMatchRoute: JobsJobIdMatchRoute,
  JobsJobIdRequirementsRoute: JobsJobIdRequirementsRoute,
  JobsJobIdSourcesRoute: JobsJobIdSourcesRoute,
  JobsJobIdIndexRoute: JobsJobIdIndexRoute,
};

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsRoute: JobsRoute,
  PipelineRoute: PipelineRoute,
  ProfileRoute: ProfileRoute,
  TodayRoute: TodayRoute,
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
  JobsCompareRoute: JobsCompareRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
